services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres12
      POSTGRES_USER: postgres
      POSTGRES_DB: auctions
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata: